"""
Open Seed v2 — Shared types for the entire pipeline.

PipelineState is the LangGraph state schema that flows through all nodes.
Every node reads from and writes to this state. Reducers (operator.add)
aggregate parallel outputs.
"""

from __future__ import annotations

import operator
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Annotated, Any, TypedDict


# ─── Enums ────────────────────────────────────────────────────────────────────


class Severity(str, Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class Verdict(str, Enum):
    PASS = "pass"
    WARN = "warn"
    BLOCK = "block"


class StepStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


class AgentProvider(str, Enum):
    CLAUDE = "claude"
    CODEX = "codex"


# ─── Data Classes ─────────────────────────────────────────────────────────────


@dataclass
class Plan:
    """Implementation plan generated by Brain."""
    summary: str = ""
    tasks: list[PlanTask] = field(default_factory=list)
    architecture: list[str] = field(default_factory=list)
    file_manifest: list[FileEntry] = field(default_factory=list)
    estimated_complexity: str = "moderate"


@dataclass
class PlanTask:
    """A single task within a plan."""
    id: str = ""
    description: str = ""
    assigned_to: AgentProvider = AgentProvider.CLAUDE
    role: str = "executor"
    dependencies: list[str] = field(default_factory=list)
    files: list[str] = field(default_factory=list)


@dataclass
class FileEntry:
    """A file in the design manifest."""
    path: str = ""
    purpose: str = ""
    layer: str = "shared"
    owner: str = "executor"
    wave: int = 1


@dataclass
class Implementation:
    """Code output from Left/Right hand agents."""
    summary: str = ""
    files_created: list[str] = field(default_factory=list)
    files_modified: list[str] = field(default_factory=list)
    commands_run: list[str] = field(default_factory=list)
    agent: AgentProvider = AgentProvider.CLAUDE
    raw_output: str = ""


@dataclass
class Finding:
    """A single QA finding from a specialist reviewer."""
    agent: str = ""
    severity: Severity = Severity.MEDIUM
    title: str = ""
    description: str = ""
    file: str = ""
    line: int | None = None
    suggestion: str = ""
    confidence: str = "medium"


@dataclass
class QAResult:
    """Aggregated QA gate result."""
    verdict: Verdict = Verdict.PASS
    findings: list[Finding] = field(default_factory=list)
    agents_run: list[str] = field(default_factory=list)
    synthesis: str = ""
    duration_ms: int = 0


@dataclass
class DeployResult:
    """Deployment outcome."""
    success: bool = False
    channel: str = ""
    url: str = ""
    message: str = ""
    timestamp: datetime = field(default_factory=datetime.now)


@dataclass
class Memory:
    """A stored memory entry."""
    id: str = ""
    content: str = ""
    memory_type: str = "semantic"  # semantic, episodic, procedural
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=datetime.now)


@dataclass
class Error:
    """A pipeline error."""
    step: str = ""
    message: str = ""
    severity: Severity = Severity.MEDIUM
    resolved: bool = False
    resolution: str = ""
    timestamp: datetime = field(default_factory=datetime.now)


@dataclass
class StepResult:
    """Result of a single pipeline step."""
    step_id: str = ""
    step_type: str = ""
    status: StepStatus = StepStatus.PENDING
    summary: str = ""
    duration_ms: int = 0
    data: dict[str, Any] = field(default_factory=dict)


# ─── LangGraph Pipeline State ────────────────────────────────────────────────


class PipelineState(TypedDict):
    """
    The shared state that flows through the LangGraph StateGraph.

    Every node reads from and writes to this state.
    Fields with Annotated[list, operator.add] use reducers to aggregate
    parallel outputs (e.g., multiple QA findings from parallel reviewers).
    """
    # Input
    task: str
    working_dir: str

    # Planning
    plan: Plan | None

    # Implementation
    implementation: Implementation | None

    # QA
    qa_result: QAResult | None

    # Sisyphus loop
    retry_count: int
    max_retries: int

    # Deployment
    deploy_result: DeployResult | None

    # Memory
    relevant_memories: list[Memory]

    # Accumulated across parallel nodes (reducers)
    errors: Annotated[list[Error], operator.add]
    messages: Annotated[list[str], operator.add]
    step_results: Annotated[list[StepResult], operator.add]
    findings: Annotated[list[Finding], operator.add]
