"""
Open Seed v2 — Pull Request deploy channel (OpenHands pattern).

After fixing an issue, automatically creates a PR with the changes.
Uses gh CLI (OAuth) — no API keys.

Pattern from: openhands/resolver/resolve_issue.py
"""

from __future__ import annotations

from openseed_core.subprocess import run_simple

from openseed_deploy.channels.base import DeployChannel
from openseed_deploy.types import ChannelResult


class PRChannel(DeployChannel):
    """Create a GitHub Pull Request with the pipeline's changes."""

    def __init__(self, base_branch: str = "main") -> None:
        self.base_branch = base_branch

    @property
    def name(self) -> str:
        return "pr"

    async def check(self) -> bool:
        """Check gh CLI is available and authenticated."""
        result = await run_simple(["gh", "auth", "status"], timeout_seconds=5)
        return result.exit_code == 0

    async def deploy(
        self,
        working_dir: str,
        message: str = "",
        issue_number: int | None = None,
        branch_name: str | None = None,
    ) -> ChannelResult:
        """
        Create a PR from the current changes.

        Steps:
        1. Create a new branch (openseed/fix-{issue_number})
        2. Commit all changes
        3. Push the branch
        4. Create PR via gh CLI

        Args:
            working_dir: Project directory with changes
            message: PR title/description
            issue_number: Optional issue number to link
            branch_name: Override branch name

        Returns:
            ChannelResult with PR URL
        """
        import os

        if not os.path.isdir(os.path.join(working_dir, ".git")):
            return ChannelResult(
                channel="pr",
                success=False,
                message="Not a git repository",
            )

        # 1. Create branch
        branch = branch_name or f"openseed/fix-{issue_number or 'auto'}"
        result = await run_simple(
            ["git", "checkout", "-b", branch],
            cwd=working_dir,
            timeout_seconds=10,
        )
        if result.exit_code != 0:
            # Branch might already exist — try checking it out
            fallback = await run_simple(
                ["git", "checkout", branch],
                cwd=working_dir,
                timeout_seconds=10,
            )
            if fallback.exit_code != 0:
                return ChannelResult(
                    channel="pr",
                    success=False,
                    message=f"Branch checkout failed: {fallback.stderr[:200]}",
                )

        # 2. Stage and commit
        await run_simple(["git", "add", "."], cwd=working_dir)
        commit_msg = message or f"openseed: fix #{issue_number}" if issue_number else "openseed: automated fix"
        commit = await run_simple(
            ["git", "commit", "-m", commit_msg],
            cwd=working_dir,
            timeout_seconds=10,
        )
        if commit.exit_code != 0 and "nothing to commit" not in commit.stdout:
            return ChannelResult(
                channel="pr",
                success=False,
                message=f"Commit failed: {commit.stderr[:200]}",
            )

        # 3. Push branch
        push = await run_simple(
            ["git", "push", "-u", "origin", branch],
            cwd=working_dir,
            timeout_seconds=30,
        )
        if push.exit_code != 0:
            return ChannelResult(
                channel="pr",
                success=False,
                message=f"Push failed: {push.stderr[:200]}",
            )

        # 4. Create PR
        pr_title = message or f"Fix #{issue_number}" if issue_number else "Automated fix by Open Seed"
        pr_body = _build_pr_body(issue_number, commit_msg)

        pr_cmd = [
            "gh",
            "pr",
            "create",
            "--title",
            pr_title,
            "--body",
            pr_body,
            "--base",
            self.base_branch,
        ]

        pr = await run_simple(pr_cmd, cwd=working_dir, timeout_seconds=30)
        if pr.exit_code != 0:
            return ChannelResult(
                channel="pr",
                success=False,
                message=f"PR creation failed: {pr.stderr[:200]}",
            )

        pr_url = pr.stdout.strip()
        return ChannelResult(
            channel="pr",
            success=True,
            message=f"PR created: {pr_url}",
            url=pr_url,
        )


def _build_pr_body(issue_number: int | None, commit_msg: str) -> str:
    """Build PR description body."""
    parts = ["## Summary", "Automated fix by Open Seed v2 pipeline.\n"]
    if issue_number:
        parts.append(f"Closes #{issue_number}\n")
    parts.append("## Changes")
    parts.append(f"{commit_msg}\n")
    parts.append("---")
    parts.append("*Generated by [Open Seed](https://github.com/sueun-dev/open-seed)*")
    return "\n".join(parts)
